(("default" . ((user-emacs-directory . "~/.config/emacs-rgoulter")))
 ("spacemacs" . ((user-emacs-directory . "~/spacemacs")))
 ("prelude" . ((user-emacs-directory . "~/prelude")))
 ("doom" . ((user-emacs-directory . "~/doom-emacs")
            (env . (("DOOMDIR" . "~/.doom.d"))))))
