format = """
($custom\n)\
($aws\n)\
($gcloud\n)\
($openstack\n)\
($terraform\n)\
($kubernetes\n)\
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\n\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$vagrant\
$zig\n\
$conda\
$memory_usage\
$env_var\
$crystal\
$nix_shell\n\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[aws]
format = '${symbol}AWS: [($profile )(\($region\) )(\[$duration\])]($style)'

[gcloud]
format = '${symbol}GCP: [$active $account(@$domain)]($style)( in [$project (\($region\))]($style))'

[kubernetes]
disabled = false
format = 'Kubernetes: [$symbol$context( \(using namespace $namespace\))]($style)'

[openstack]
format = "${symbol}OpenStack: [$cloud(\\($project\\))]($style)"

[status]
disabled = false

[terraform]
format = "${symbol}Terraform: ([$version]($style) )in [$workspace]($style) workspace"

[custom.toolbox]
description = "The activated toolbox container"
command = " bash -c 'echo $(. /var/run/.containerenv; echo ${name}:${image})' "
when = """ bash -c "[[ -f /run/.containerenv && -f /run/.toolboxenv ]]" """
style = "bold red"
format = "[\\[$output\\]]($style) "
disabled = false
