format = """
($aws\n)\
($gcloud\n)\
($openstack\n)\
($terraform\n)\
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[aws]
format = '${symbol}AWS: [($profile )(\($region\) )(\[$duration\])]($style)'

[gcloud]
format = '${symbol}GCP: [$active $account(@$domain)]($style)( in [$project (\($region\))]($style))'

[openstack]
format = "${symbol}OpenStack: [$cloud(\\($project\\))]($style)"

[terraform]
format = "${symbol}Terraform: ([$version]($style) )in [$workspace]($style) workspace"
